### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by sezan92** [Willy0919/Evovling_Boxes#3]
Hello I was trying to run your demo.py code after installing caffe. But the error is showing
Traceback (most recent call last):
  File "tools/demo.py", line 28, in <module>
    import caffe, os, sys, cv2
  File "/home/sezan92/Documents/Evolving_Boxes/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/sezan92/Documents/Evolving_Boxes/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe
I have installed the py_fast_r_cnn github repo and the demo.py code run as well

**Comment by z362194037** [comment]
@sezan92 all you need to do is to add a __init__.py in the datasets folder

**Comment by JasonZhao001** [comment]
you should make pycaffe 
and then PYTHONPATH=/path/caffe/python:$PYTHONPATH
